server:
  port: 8080

jwt:
  secret:
    access: and0LnNlY3JldC5hY2Nlc3Muand0LnNlY3JldC5hY2Nlc3M=
    refresh: and0LnNlY3JldC5yZWZyZXNoLmp3dC5zZWNyZXQucmVmcmVzaA==

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/semester
    username: postgres
    password: stilinski
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smpt.gmail.com
    username: "mironsolopov24@gmail.com"
    password: "ttzncsknzzibtbbf"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true

  liquibase:
    enabled: false
    change-log: classpath:/db/changelog/db-changelog.xml
    url: jdbc:postgresql://localhost:5432/semester
    user: postgres
    password: stilinski
    driver-class-name: org.postgresql.Driver


  freemarker:
    template-loader-path: /WEB-INF/templates/
    suffix: .ftl

mail:
  content: "Dear {name}, please follow the link below for verify your account: <a href={url}>VERIFY<a/>"
  from: "mironsolopov24@gmail.com"
  sender: Test Application
  subject: Please verify your account

